<?php /** @var Thecoachsmb\Mymodule\Block\Art $block */ ?>
<?php  $articleCollection = $block->getCollection();?>
<?php if (count($articleCollection)) { ?>
<h2><?= $block->escapeHtml(__('My-own-module Table')) ?></h2>
<?php foreach($articleCollection as $post): ?>
<h3><?= $block->escapeHtml(__('Articlessss - ')) ?>
<a href="<?php echo $block->getArticleUrl($post->getId());?>"><?php echo $post->getTitle(); ?></a>
</h3>

<p><?php echo $post->getId(); ?></p>
<?php endforeach; ?>
<?php } ?>