<?php $articleCollection = $block->getCollection(); ?>
<?php if (count($articleCollection)) { ?>
    <div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Teja Blog') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col title"><?php echo __('Title') ?></th>
            <th scope="col" class="col description"><?php echo __('Description') ?></th>
            <th scope="col" class="col status"><?php echo __('Status') ?></th>
            <th scope="col" class="col status"><?php echo __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
 foreach ($articleCollection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Title')) ?>" class="col title">
                <a href="<?php echo $block->getArticleUrl($item->getId());?>"><?php echo $item->getTitle(); ?></a>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Description')) ?>" class="col description">
                <?php echo $item->getDescription() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                class="col status"><?php echo $item->getStatus(); ?></td>
            <td data-th="<?= $block->escapeHtml(__('Delete')) ?>" class="col title">
                <a href="<?php echo $block->getDeleteUrl($item->getId());?>"><?php echo 'Delete'; ?></a>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php } ?> 